### ISSUE TITLE
Flutter navigation SDK crash in Android 

### ISSUE THREAD

**Issue by SatishKumar2590** [googlemaps/flutter-navigation-sdk#171] opened 2024-10-07 04:04 UTC
---
**Crash summary**

A crash is very frequently occurring at GoogleMapsNavigationSessionManager.getNavigator in Android 
---

#### Environment details

1. com.google.maps.flutter.navigation.FlutterError - Cannot access navigation functionality before the navigation session has been initialized.
2. Android 14, Samsung Galaxy A15 5G
3. google_navigation_flutter: ^0.3.0

#### Stack trace
```
# From firebase has been attached 
```
[Firebase_v2_stacktrace.txt](https://github.com/user-attachments/files/17272594/Firebase_v2_stacktrace.txt)

Thanks!

**Comment by jokerttu** [comment] 2024-10-09 06:54
Hi @SatishKumar2590 

This error is thrown by the platform implementation
```kotlin
@Throws(FlutterError::class)
  fun getNavigator(): Navigator {
    if (navigator != null) {
      return navigator!!
    } else {
      throw FlutterError(
        "sessionNotInitialized",
        "Cannot access navigation functionality before the navigation session has been initialized."
      )
    }
  }
  ```
  
And happens if navigator is not initialized before using it.
 
Make sure navigation is initialized with:
`await GoogleMapsNavigator.initializeNavigationSession();`

Check instructions at [README.md](https://github.com/googlemaps/flutter-navigation-sdk/blob/main/README.md).

There is also method which can be used to check if navigator is initialized and can be used:
`bool initialized = await GoogleMapsNavigator.isInitialized()`

Closing this issue as this is not a bug.

If this happens even if navigation session is active, please reopen this issue with more information where this happens.

**Closed by jokerttu** 2024-10-09 06:54 UTC
Labels: type: bug, priority: p1
